"""initial schema v2

Revision ID: 118b7160b30d
Revises: 
Create Date: 2026-09-01 16:21:06.038520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '118b7160b30d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_cities',
    sa.Column('id', sa.Integer(), nullable=False, comment='市区町村ID'),
    sa.Column('prefecture', sa.String(length=20), nullable=False, comment='都道府県名'),
    sa.Column('parent_city', sa.String(length=50), nullable=True, comment='政令指定都市名（例: 横浜市）。特別区・一般市町村は NULL'),
    sa.Column('city_name', sa.String(length=100), nullable=False, comment='区市町村名'),
    sa.Column('canonical_name', sa.String(length=150), nullable=False, comment='YAML に記述する正規名。同一都道府県内で一意。政令市の区は市名を prefix する（例: 横浜市西区）'),
    sa.Column('jis_code', sa.String(length=5), nullable=True, comment='全国地方公共団体コードの上位5桁（JIS X 0402 相当）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード更新日時'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_m_cities')),
    sa.UniqueConstraint('prefecture', 'canonical_name', name=op.f('uq_m_cities_prefecture_canonical_name')),
    comment='市区町村マスタ（YAML の cities に指定する canonical_name の正典）'
    )
    op.create_table('m_condition_categories',
    sa.Column('id', sa.Integer(), nullable=False, comment='条件カテゴリID'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='カテゴリコード（例: SECURITY）'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='カテゴリ名'),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='表示順（昇順）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード更新日時'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_m_condition_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_m_condition_categories_code')),
    comment='検索条件のカテゴリマスタ'
    )
    op.create_table('m_property_types',
    sa.Column('id', sa.Integer(), nullable=False, comment='物件種別ID'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='物件種別コード（例: CHINTAI）'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='物件種別名'),
    sa.Column('family', sa.String(length=20), nullable=False, comment='種別ファミリ。metric体系・dedup_key構成要素・YAMLスキーマの分岐単位。CHINTAI=賃貸 / MANSION_BUY=マンション売買 / KODATE_BUY=戸建て売買'),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='表示順（昇順）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード更新日時'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_m_property_types')),
    sa.UniqueConstraint('code', name=op.f('uq_m_property_types_code')),
    comment='物件種別マスタ（賃貸・新築M・中古M・新築K・中古K）'
    )
    op.create_table('m_sites',
    sa.Column('id', sa.Integer(), nullable=False, comment='サイトID'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='サイトコード（例: SUUMO）'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='サイト名'),
    sa.Column('base_url', sa.String(length=255), nullable=True, comment='サイトのベースURL（スキームとホストまで）'),
    sa.Column('fetch_method', sa.String(length=20), server_default=sa.text("'HTTP'"), nullable=False, comment='取得方式。HTTP=httpx+lxml / PLAYWRIGHT=ブラウザ自動化が必要'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='スクレイピング対象として有効か'),
    sa.Column('min_interval_sec', sa.Numeric(precision=5, scale=2), server_default=sa.text('2.5'), nullable=False, comment='同一サイトへの最小リクエスト間隔（秒）。実際は±30%のジッタを乗せる'),
    sa.Column('max_pages_per_run', sa.Integer(), server_default=sa.text('5'), nullable=False, comment='1回の実行で取得する一覧ページ数の上限'),
    sa.Column('daily_request_cap', sa.Integer(), nullable=True, comment='1日あたりのリクエスト数上限。NULL=無制限'),
    sa.Column('representative_priority', sa.Integer(), server_default=sa.text('100'), nullable=False, comment='名寄せグループの代表選定でのサイト優先順（小さいほど優先）。価格・抽出情報数で決着しなかった場合のタイブレークに使う'),
    sa.Column('notes', sa.Text(), nullable=True, comment='運用上の備考'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード更新日時'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_m_sites')),
    sa.UniqueConstraint('code', name=op.f('uq_m_sites_code')),
    comment='スクレイピング対象サイトマスタ'
    )
    op.create_table('t_ranking_digests',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='ダイジェストID'),
    sa.Column('pattern_name', sa.String(length=255), nullable=False, comment='検索パターン名'),
    sa.Column('digest_group', sa.String(length=100), nullable=True, comment='ダイジェストのセクション並記グループ。同一グループのパターンを1メッセージに並べる。スコアは種別間で混ぜない'),
    sa.Column('top_n', sa.Integer(), nullable=False, comment='掲載した件数'),
    sa.Column('property_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='掲載した物件IDの配列（順位順）'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'sent'"), nullable=False, comment='送信結果。sent / failed'),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='送信を試みた日時'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード作成日時'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t_ranking_digests')),
    comment='日次ランキングダイジェストの送信履歴（追記専用）'
    )
    op.create_table('t_scrape_logs',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='ログID'),
    sa.Column('run_id', sa.UUID(), nullable=True, comment='t_scrape_runs.run_id と対応する実行識別子'),
    sa.Column('level', sa.String(length=10), nullable=False, comment='ログレベル。INFO / WARN / ERROR'),
    sa.Column('site_code', sa.String(length=50), nullable=True, comment='サイトコード'),
    sa.Column('pattern_name', sa.String(length=255), nullable=True, comment='検索パターン名'),
    sa.Column('message', sa.Text(), nullable=False, comment='ログ本文'),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='付随情報（URL・例外内容等）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード作成日時'),
    sa.CheckConstraint("level IN ('INFO', 'WARN', 'ERROR')", name=op.f('ck_t_scrape_logs_scrape_logs_level')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t_scrape_logs')),
    comment='スクレイピングの実行ログ（全件永久保持）'
    )
    op.create_index('ix_t_scrape_logs_created_at', 't_scrape_logs', ['created_at'], unique=False)
    op.create_index('ix_t_scrape_logs_level', 't_scrape_logs', ['level'], unique=False)
    op.create_table('m_city_site_values',
    sa.Column('city_id', sa.Integer(), nullable=False, comment='市区町村ID'),
    sa.Column('site_id', sa.Integer(), nullable=False, comment='サイトID'),
    sa.Column('value', sa.String(length=500), nullable=False, comment='そのサイトの検索URLに埋める値。パスセグメント（例: sc_shinjuku）・スラグ（例: tokyo/shinjuku）・JIS5桁コード（例: 13104）のいずれか。サイトごとの解釈は m_sites 側の実装に従う'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード更新日時'),
    sa.ForeignKeyConstraint(['city_id'], ['m_cities.id'], name=op.f('fk_m_city_site_values_city_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['m_sites.id'], name=op.f('fk_m_city_site_values_site_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('city_id', 'site_id', name=op.f('pk_m_city_site_values')),
    comment='市区町村×サイトのURL検索値（縦持ち）'
    )
    op.create_table('m_conditions',
    sa.Column('id', sa.Integer(), nullable=False, comment='条件ID'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='条件カテゴリID'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='条件コード（例: SEC_AUTOLOCK）'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='条件名'),
    sa.Column('description', sa.Text(), nullable=True, comment='条件の補足説明'),
    sa.Column('data_type', sa.String(length=50), server_default=sa.text("'boolean'"), nullable=False, comment='値の型。boolean=有無 / range=下限上限 / enum=選択肢 / number=数値単体'),
    sa.Column('is_extractable', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='詳細ページ本文からのローカル抽出対象か。true の条件だけが m_condition_synonyms の辞書を持ち t_property_features に載る。エリア・価格上限のような検索軸そのものは false'),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='カテゴリ内の表示順（昇順）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード更新日時'),
    sa.ForeignKeyConstraint(['category_id'], ['m_condition_categories.id'], name=op.f('fk_m_conditions_category_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_m_conditions')),
    sa.UniqueConstraint('code', name=op.f('uq_m_conditions_code')),
    comment='検索条件マスタ（設備・特性・価格条件等）'
    )
    op.create_table('t_properties',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='物件ID'),
    sa.Column('site_id', sa.Integer(), nullable=False, comment='取得元サイトID'),
    sa.Column('property_type_id', sa.Integer(), nullable=False, comment='物件種別ID'),
    sa.Column('external_id', sa.String(length=500), nullable=False, comment='サイト固有の物件ID（サイト内で一意）'),
    sa.Column('url', sa.Text(), nullable=False, comment='詳細ページURL'),
    sa.Column('title', sa.String(length=500), nullable=True, comment='物件名・掲載タイトル'),
    sa.Column('price', sa.BigInteger(), nullable=True, comment='現在価格（円）。賃貸=月額賃料、売買=物件価格。レンジ表示ならその下限。未定は NULL'),
    sa.Column('price_prev', sa.BigInteger(), nullable=True, comment='直前の価格（円）。価格変動通知の差分算出に使う'),
    sa.Column('price_min', sa.BigInteger(), nullable=True, comment='価格レンジ下限（円）。新築の棟単位掲載向け'),
    sa.Column('price_max', sa.BigInteger(), nullable=True, comment='価格レンジ上限（円）。新築の棟単位掲載向け'),
    sa.Column('mgmt_fee_monthly', sa.BigInteger(), nullable=True, comment='管理費・共益費（円/月）。賃貸・マンション売買の双方で使う'),
    sa.Column('repair_reserve_monthly', sa.BigInteger(), nullable=True, comment='修繕積立金（円/月）。マンション売買のみ'),
    sa.Column('deposit_amount', sa.BigInteger(), nullable=True, comment='敷金・保証金（円）'),
    sa.Column('key_money_amount', sa.BigInteger(), nullable=True, comment='礼金（円）'),
    sa.Column('rent_total', sa.BigInteger(), sa.Computed('CASE WHEN price IS NULL THEN NULL ELSE price + COALESCE(mgmt_fee_monthly, 0) END', persisted=True), nullable=True, comment='賃料＋管理費（円/月）の生成列。metric rent_total の入力。price が NULL なら NULL'),
    sa.Column('price_per_sqm', sa.Numeric(precision=12, scale=2), nullable=True, comment='㎡単価（円/㎡）。表示用の派生値であり metric にはしない（price と area に既に weight を配れるため二重に重みが掛かる）'),
    sa.Column('area_sqm', sa.Numeric(precision=8, scale=2), nullable=True, comment='専有面積（㎡）。賃貸・マンションのみ。戸建てには使わない'),
    sa.Column('land_area_sqm', sa.Numeric(precision=10, scale=2), nullable=True, comment='土地面積（㎡）。戸建てのみ'),
    sa.Column('building_area_sqm', sa.Numeric(precision=10, scale=2), nullable=True, comment='建物面積（㎡）。戸建てのみ'),
    sa.Column('layout', sa.String(length=50), nullable=True, comment='間取り（例: 1LDK）'),
    sa.Column('floor_num', sa.Integer(), nullable=True, comment='所在階。地下は負値'),
    sa.Column('total_floors', sa.Integer(), nullable=True, comment='建物の地上階数'),
    sa.Column('built_on', sa.Date(), nullable=True, comment='築年月。日は1日に固定して格納する'),
    sa.Column('age_years', sa.Integer(), nullable=True, comment='築年数（年）。築年月が取れないサイト向けに掲載値をそのまま保持'),
    sa.Column('address', sa.Text(), nullable=True, comment='住所（掲載原文）'),
    sa.Column('address_normalized', sa.Text(), nullable=True, comment='正規化住所。dedup_key の入力に使う'),
    sa.Column('prefecture', sa.String(length=20), nullable=True, comment='都道府県名'),
    sa.Column('city_id', sa.Integer(), nullable=True, comment='市区町村ID。住所から解決できた場合のみ'),
    sa.Column('station_info', sa.Text(), nullable=True, comment='最寄り駅情報（掲載原文）'),
    sa.Column('walk_minutes', sa.Integer(), nullable=True, comment='最寄り駅からの徒歩分数。複数駅ある場合は最短'),
    sa.Column('image_url', sa.Text(), nullable=True, comment='サムネイル画像URL'),
    sa.Column('raw_features_text', sa.Text(), nullable=True, comment='詳細ページの設備ブロック原文（テキストのみ。HTML全体は保存しない）。辞書を改善したとき再スクレイピングせず re-extract で全件再抽出するための保存'),
    sa.Column('type_specific_attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='種別固有の非正規化属性。接道・建ぺい率/容積率・権利形態・引渡時期・建築条件付きフラグ・price_undecided 等。表記揺れが激しく型付け列に向かない項目を置く'),
    sa.Column('dedup_key', sa.String(length=64), nullable=True, comment='名寄せキー（SHA256 hex）。t_property_groups.dedup_key と対応'),
    sa.Column('group_id', sa.BigInteger(), nullable=True, comment='名寄せグループID。未グループ化は NULL'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False, comment='掲載状態。active=掲載中 / sold=成約済み / removed=掲載終了'),
    sa.Column('detail_fetched_at', sa.DateTime(timezone=True), nullable=True, comment='詳細ページの最終取得日時。NULL=未取得（詳細取得キューの対象）'),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='掲載を初めて観測した日時'),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='一覧に掲載されていることを最後に確認した日時'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード更新日時'),
    sa.CheckConstraint("status IN ('active', 'sold', 'removed')", name=op.f('ck_t_properties_properties_status')),
    sa.ForeignKeyConstraint(['city_id'], ['m_cities.id'], name=op.f('fk_t_properties_city_id')),
    sa.ForeignKeyConstraint(['group_id'], ['t_property_groups.id'], name=op.f('fk_t_properties_group_id'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['property_type_id'], ['m_property_types.id'], name=op.f('fk_t_properties_property_type_id')),
    sa.ForeignKeyConstraint(['site_id'], ['m_sites.id'], name=op.f('fk_t_properties_site_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t_properties')),
    sa.UniqueConstraint('site_id', 'external_id', name=op.f('uq_t_properties_site_id_external_id')),
    comment='物件（1行=1サイト掲載）'
    )
    op.create_index('ix_t_properties_dedup_key', 't_properties', ['dedup_key'], unique=False, postgresql_where='dedup_key IS NOT NULL')
    op.create_index('ix_t_properties_detail_pending', 't_properties', ['site_id'], unique=False, postgresql_where="detail_fetched_at IS NULL AND status = 'active'")
    op.create_index('ix_t_properties_group_id', 't_properties', ['group_id'], unique=False, postgresql_where='group_id IS NOT NULL')
    op.create_index('ix_t_properties_status', 't_properties', ['status'], unique=False)
    op.create_table('t_property_groups',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='グループID'),
    sa.Column('dedup_key', sa.String(length=64), nullable=False, comment='名寄せキー（SHA256 hex）。ファミリ識別子＋正規化住所＋種別ごとの構成要素から生成。賃貸/マンション=間取り＋専有面積＋階数、戸建て=土地面積＋建物面積＋間取り。建物名は賃貸で非公開・伏字が多く偽陰性の主因になるため含めない'),
    sa.Column('property_type_id', sa.Integer(), nullable=False, comment='物件種別ID'),
    sa.Column('representative_property_id', sa.BigInteger(), nullable=True, comment='代表物件ID。月額/価格が最安 → 設備抽出数が最多 → サイト優先順 で選定'),
    sa.Column('member_count', sa.Integer(), server_default=sa.text('1'), nullable=False, comment='グループに属する掲載件数'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード更新日時'),
    sa.ForeignKeyConstraint(['property_type_id'], ['m_property_types.id'], name=op.f('fk_t_property_groups_property_type_id')),
    sa.ForeignKeyConstraint(['representative_property_id'], ['t_properties.id'], name=op.f('fk_t_property_groups_representative_property_id'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t_property_groups')),
    sa.UniqueConstraint('dedup_key', name=op.f('uq_t_property_groups_dedup_key')),
    comment='クロスサイト名寄せグループ'
    )
    op.create_table('t_scrape_runs',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='実行レコードID'),
    sa.Column('run_id', sa.UUID(), nullable=False, comment='1回の実行を束ねる識別子'),
    sa.Column('mode', sa.String(length=20), nullable=False, comment='実行モード。scan=増分 / seed=通知なしの記録専用 / full=全量 / check-sold=成約確認 / digest=ダイジェスト / rescore=再スコア'),
    sa.Column('pattern_name', sa.String(length=255), nullable=True, comment='検索パターン名'),
    sa.Column('site_id', sa.Integer(), nullable=True, comment='対象サイトID'),
    sa.Column('phase', sa.String(length=30), nullable=True, comment='処理フェーズ。list / detail / extract / score / notify'),
    sa.Column('cursor', sa.Text(), nullable=True, comment='再開位置（ページ番号・最終処理物件ID等）'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'running'"), nullable=False, comment='実行状態'),
    sa.Column('items_seen', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='観測した件数'),
    sa.Column('items_new', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='新規登録した件数'),
    sa.Column('items_failed', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='処理に失敗した件数'),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='開始日時'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='終了日時。running の間は NULL'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード更新日時'),
    sa.CheckConstraint("status IN ('running', 'completed', 'failed', 'aborted')", name=op.f('ck_t_scrape_runs_scrape_runs_status')),
    sa.ForeignKeyConstraint(['site_id'], ['m_sites.id'], name=op.f('fk_t_scrape_runs_site_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t_scrape_runs')),
    comment='スクレイピング実行のチェックポイント'
    )
    op.create_index('ix_t_scrape_runs_run_id', 't_scrape_runs', ['run_id'], unique=False)
    op.create_table('t_unknown_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='未知表記ID'),
    sa.Column('token', sa.String(length=200), nullable=False, comment='正規化済みトークン（NFKC・小文字化後）'),
    sa.Column('site_id', sa.Integer(), nullable=False, comment='観測したサイトID'),
    sa.Column('property_family', sa.String(length=20), nullable=True, comment='観測した種別ファミリ。辞書の賃貸/売買どちらに足すかの判断材料'),
    sa.Column('occurrence_count', sa.BigInteger(), server_default=sa.text('1'), nullable=False, comment='累計出現回数'),
    sa.Column('sample_url', sa.Text(), nullable=True, comment='出現した物件の詳細URL（例示用）'),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='初回観測日時'),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最終観測日時'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード更新日時'),
    sa.ForeignKeyConstraint(['site_id'], ['m_sites.id'], name=op.f('fk_t_unknown_tokens_site_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t_unknown_tokens')),
    sa.UniqueConstraint('token', 'site_id', name=op.f('uq_t_unknown_tokens_token_site_id')),
    comment='辞書未登録の設備表記（辞書育成の入力）'
    )
    op.create_index('ix_t_unknown_tokens_occurrence_count', 't_unknown_tokens', ['occurrence_count'], unique=False)
    op.create_table('m_condition_property_types',
    sa.Column('id', sa.Integer(), nullable=False, comment='マッピングID'),
    sa.Column('condition_id', sa.Integer(), nullable=False, comment='条件ID'),
    sa.Column('property_type_id', sa.Integer(), nullable=False, comment='物件種別ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード更新日時'),
    sa.ForeignKeyConstraint(['condition_id'], ['m_conditions.id'], name=op.f('fk_m_condition_property_types_condition_id')),
    sa.ForeignKeyConstraint(['property_type_id'], ['m_property_types.id'], name=op.f('fk_m_condition_property_types_property_type_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_m_condition_property_types')),
    sa.UniqueConstraint('condition_id', 'property_type_id', name=op.f('uq_m_condition_property_types_condition_id_property_type_id')),
    comment='条件×物件種別マッピング（条件の適用可能種別）'
    )
    op.create_table('m_condition_synonyms',
    sa.Column('id', sa.Integer(), nullable=False, comment='辞書エントリID'),
    sa.Column('condition_id', sa.Integer(), nullable=False, comment='条件ID'),
    sa.Column('site_id', sa.Integer(), nullable=True, comment='サイト固有パターンの場合のサイトID。NULL=全サイト共通'),
    sa.Column('property_family', sa.String(length=20), nullable=True, comment='適用する種別ファミリ（CHINTAI / MANSION_BUY / KODATE_BUY）。NULL=全ファミリ。売買の証明書・性能評価系の語彙は賃貸と別体系のため辞書を2部構成にする'),
    sa.Column('pattern', sa.Text(), nullable=False, comment='照合する表記（NFKC正規化・小文字化した後の形で保持）'),
    sa.Column('is_negative', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='否定パターンか（例:「オートロックなし」。true にマッチしたら条件は不成立）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード更新日時'),
    sa.ForeignKeyConstraint(['condition_id'], ['m_conditions.id'], name=op.f('fk_m_condition_synonyms_condition_id')),
    sa.ForeignKeyConstraint(['site_id'], ['m_sites.id'], name=op.f('fk_m_condition_synonyms_site_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_m_condition_synonyms')),
    sa.UniqueConstraint('condition_id', 'site_id', 'pattern', 'is_negative', name=op.f('uq_m_condition_synonyms_condition_id_site_id_pattern_is_negative'), postgresql_nulls_not_distinct=True),
    comment='設備抽出辞書（条件コード → 表記パターン）'
    )
    op.create_table('t_notifications',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='通知ID'),
    sa.Column('property_id', sa.BigInteger(), nullable=False, comment='物件ID'),
    sa.Column('group_id', sa.BigInteger(), nullable=True, comment='名寄せグループID。重複抑制はグループ単位で行う'),
    sa.Column('pattern_name', sa.String(length=255), nullable=False, comment='検索パターン名'),
    sa.Column('notification_type', sa.String(length=20), nullable=False, comment='通知種別。new=新着/再掲載 / sold=成約 / price_up=値上がり / price_down=値下がり / cheaper_listing=同一物件の他サイト安値掲載'),
    sa.Column('price_at_notify', sa.BigInteger(), nullable=True, comment='通知時点の価格（円）。価格変動の重複判定に使う'),
    sa.Column('score_at_notify', sa.Numeric(precision=6, scale=3), nullable=True, comment='通知時点のWANTスコア（0〜100）'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'sent'"), nullable=False, comment='送信結果。sent / failed'),
    sa.Column('notified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='送信を試みた日時'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード作成日時'),
    sa.CheckConstraint("notification_type IN ('new', 'sold', 'price_up', 'price_down', 'cheaper_listing')", name=op.f('ck_t_notifications_notifications_type')),
    sa.ForeignKeyConstraint(['group_id'], ['t_property_groups.id'], name=op.f('fk_t_notifications_group_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['t_properties.id'], name=op.f('fk_t_notifications_property_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t_notifications')),
    comment='個別通知の送信履歴（追記専用）'
    )
    op.create_index('ix_t_notifications_pattern_name', 't_notifications', ['pattern_name'], unique=False)
    op.create_index('ix_t_notifications_property_type', 't_notifications', ['property_id', 'notification_type'], unique=False)
    op.create_table('t_property_features',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='抽出結果ID'),
    sa.Column('property_id', sa.BigInteger(), nullable=False, comment='物件ID'),
    sa.Column('condition_id', sa.Integer(), nullable=False, comment='条件ID'),
    sa.Column('source', sa.String(length=20), server_default=sa.text("'DETAIL'"), nullable=False, comment='抽出元。LIST=一覧ページ / DETAIL=詳細ページ / SITE_TAG=サイトの構造化タグ'),
    sa.Column('matched_text', sa.Text(), nullable=True, comment='マッチした原文の断片。辞書の誤爆調査に使う'),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='抽出を実行した日時。辞書更新後の再抽出で更新される'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード更新日時'),
    sa.ForeignKeyConstraint(['condition_id'], ['m_conditions.id'], name=op.f('fk_t_property_features_condition_id')),
    sa.ForeignKeyConstraint(['property_id'], ['t_properties.id'], name=op.f('fk_t_property_features_property_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t_property_features')),
    sa.UniqueConstraint('property_id', 'condition_id', name=op.f('uq_t_property_features_property_id_condition_id')),
    comment='物件の設備・特性抽出結果'
    )
    op.create_table('t_property_scores',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='スコアID'),
    sa.Column('property_id', sa.BigInteger(), nullable=False, comment='物件ID'),
    sa.Column('pattern_name', sa.String(length=255), nullable=False, comment='検索パターン名（YAML の name）'),
    sa.Column('must_result', sa.String(length=10), nullable=False, comment='MUST判定の3値。pass=全充足 / fail=未充足あり（詳細取得もスキップ） / unknown=判定不能項目あり。unknown の扱いは YAML の must.unknown_policy に従う'),
    sa.Column('score', sa.Numeric(precision=6, scale=3), nullable=True, comment='WANTスコア 0〜100点。must_result が fail の場合は NULL'),
    sa.Column('rank_in_pattern', sa.Integer(), nullable=True, comment='同一パターン内のスコア降順順位（1始まり）'),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='採点内訳。各項目の {code, name, weight, s, points, status: hit|miss|unknown}。欠損metricは missing:true を立て分子・分母の双方から除外して再正規化する'),
    sa.Column('config_hash', sa.String(length=64), nullable=False, comment='YAML のスコア関連部分のハッシュ。不一致なら自動再スコアの対象になる'),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='採点を実行した日時'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード作成日時'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='レコード更新日時'),
    sa.CheckConstraint("must_result IN ('pass', 'fail', 'unknown')", name=op.f('ck_t_property_scores_property_scores_must_result')),
    sa.ForeignKeyConstraint(['property_id'], ['t_properties.id'], name=op.f('fk_t_property_scores_property_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_t_property_scores')),
    sa.UniqueConstraint('property_id', 'pattern_name', name=op.f('uq_t_property_scores_property_id_pattern_name')),
    comment='検索パターン別のスコアリング結果'
    )
    op.create_index('ix_t_property_scores_pattern_score', 't_property_scores', ['pattern_name', 'score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_t_property_scores_pattern_score', table_name='t_property_scores')
    op.drop_table('t_property_scores')
    op.drop_table('t_property_features')
    op.drop_index('ix_t_notifications_property_type', table_name='t_notifications')
    op.drop_index('ix_t_notifications_pattern_name', table_name='t_notifications')
    op.drop_table('t_notifications')
    op.drop_table('m_condition_synonyms')
    op.drop_table('m_condition_property_types')
    op.drop_index('ix_t_unknown_tokens_occurrence_count', table_name='t_unknown_tokens')
    op.drop_table('t_unknown_tokens')
    op.drop_index('ix_t_scrape_runs_run_id', table_name='t_scrape_runs')
    op.drop_table('t_scrape_runs')
    op.drop_table('t_property_groups')
    op.drop_index('ix_t_properties_status', table_name='t_properties')
    op.drop_index('ix_t_properties_group_id', table_name='t_properties', postgresql_where='group_id IS NOT NULL')
    op.drop_index('ix_t_properties_detail_pending', table_name='t_properties', postgresql_where="detail_fetched_at IS NULL AND status = 'active'")
    op.drop_index('ix_t_properties_dedup_key', table_name='t_properties', postgresql_where='dedup_key IS NOT NULL')
    op.drop_table('t_properties')
    op.drop_table('m_conditions')
    op.drop_table('m_city_site_values')
    op.drop_index('ix_t_scrape_logs_level', table_name='t_scrape_logs')
    op.drop_index('ix_t_scrape_logs_created_at', table_name='t_scrape_logs')
    op.drop_table('t_scrape_logs')
    op.drop_table('t_ranking_digests')
    op.drop_table('m_sites')
    op.drop_table('m_property_types')
    op.drop_table('m_condition_categories')
    op.drop_table('m_cities')
    # ### end Alembic commands ###
