-- ============================================================
-- m_conditions: 条件マスタ
--
-- v1 の128条件をそのまま引き継ぎ、売買固有の20条件（CERT / LAND ほか）を追加した148条件。
-- is_extractable は「詳細ページ本文からのローカル抽出対象か」。
-- data_type='boolean' を原則 true とし、検索軸そのものである
-- AREA_BUS_OK / PRICE_INCL_MGMT / PRICE_INCL_PARKING だけ false にしている。
-- ============================================================

INSERT INTO m_conditions (category_id, code, name, description, data_type, is_extractable, sort_order)
SELECT cat.id, v.code, v.name, v.description, v.data_type, v.is_extractable, v.sort_order
FROM (VALUES
    ('AREA', 'AREA_PREF', '都道府県', NULL, 'enum', FALSE, 1),
    ('AREA', 'AREA_CITY', '市区町村', NULL, 'enum', FALSE, 2),
    ('AREA', 'AREA_STATION_LINE', '路線・駅', NULL, 'enum', FALSE, 3),
    ('AREA', 'AREA_WALK_MIN', '駅徒歩（分以内）', NULL, 'number', FALSE, 4),
    ('AREA', 'AREA_BUS_OK', 'バス利用可（含む）', NULL, 'boolean', FALSE, 5),
    ('AREA', 'AREA_COMMUTE_MIN', '通勤・通学時間（分以内）', NULL, 'number', FALSE, 6),
    ('AREA', 'AREA_TRANSFER_COUNT', '乗換回数', NULL, 'number', FALSE, 7),
    ('PRICE_RENT', 'PRICE_RENT_MIN', '家賃下限', NULL, 'range', FALSE, 1),
    ('PRICE_RENT', 'PRICE_RENT_MAX', '家賃上限', NULL, 'range', FALSE, 2),
    ('PRICE_RENT', 'PRICE_INCL_MGMT', '管理費・共益費込み', NULL, 'boolean', FALSE, 3),
    ('PRICE_RENT', 'PRICE_INCL_PARKING', '駐車場代込み', NULL, 'boolean', FALSE, 4),
    ('PRICE_RENT', 'PRICE_NO_REIKIN', '礼金なし', NULL, 'boolean', TRUE, 5),
    ('PRICE_RENT', 'PRICE_NO_SHIKIKIN', '敷金なし', NULL, 'boolean', TRUE, 6),
    ('PRICE_RENT', 'PRICE_NO_HOSHOKIN', '保証金なし', NULL, 'boolean', TRUE, 7),
    ('PRICE_RENT', 'PRICE_FREE_RENT', 'フリーレント', NULL, 'boolean', TRUE, 8),
    ('PRICE_RENT', 'PRICE_INITIAL_CARD', '初期費用カード決済可', NULL, 'boolean', TRUE, 9),
    ('PRICE_RENT', 'PRICE_RENT_CARD', '家賃カード決済可', NULL, 'boolean', TRUE, 10),
    ('PRICE_RENT', 'PRICE_NO_GUARANTOR', '保証人不要', NULL, 'boolean', TRUE, 11),
    ('PRICE_BUY', 'PRICE_BUY_MIN', '物件価格下限', NULL, 'range', FALSE, 1),
    ('PRICE_BUY', 'PRICE_BUY_MAX', '物件価格上限', NULL, 'range', FALSE, 2),
    ('PRICE_BUY', 'PRICE_MONTHLY', '月々支払額', NULL, 'range', FALSE, 3),
    ('PRICE_BUY', 'PRICE_UNDECIDED', '価格未定を含む', NULL, 'boolean', TRUE, 4),
    ('BUILDING', 'BLDG_TYPE', '建物種別', NULL, 'enum', FALSE, 1),
    ('BUILDING', 'BLDG_LAYOUT', '間取り', NULL, 'enum', FALSE, 2),
    ('BUILDING', 'BLDG_AREA_MIN', '専有面積下限（㎡）', NULL, 'range', FALSE, 3),
    ('BUILDING', 'BLDG_AREA_MAX', '専有面積上限（㎡）', NULL, 'range', FALSE, 4),
    ('BUILDING', 'BLDG_BUILD_AREA', '建物面積（㎡）', NULL, 'range', FALSE, 5),
    ('BUILDING', 'BLDG_LAND_AREA', '土地面積（㎡）', NULL, 'range', FALSE, 6),
    ('BUILDING', 'BLDG_BALCONY_AREA', 'バルコニー面積（㎡）', NULL, 'range', FALSE, 7),
    ('BUILDING', 'BLDG_AGE_MAX', '築年数（〇年以内）', NULL, 'number', FALSE, 8),
    ('STRUCTURE', 'STRUCT_RC', '鉄筋コンクリート（RC）', NULL, 'boolean', TRUE, 1),
    ('STRUCTURE', 'STRUCT_SRC', '鉄筋鉄骨コンクリート（SRC）', NULL, 'boolean', TRUE, 2),
    ('STRUCTURE', 'STRUCT_STEEL', '鉄骨造', NULL, 'boolean', TRUE, 3),
    ('STRUCTURE', 'STRUCT_WOOD', '木造', NULL, 'boolean', TRUE, 4),
    ('STRUCTURE', 'STRUCT_BLOCK', 'ブロック・その他', NULL, 'boolean', TRUE, 5),
    ('STRUCTURE', 'STRUCT_QUAKE', '耐震基準適合', NULL, 'boolean', TRUE, 6),
    ('STRUCTURE', 'STRUCT_LONGEVITY', '長期優良住宅', NULL, 'boolean', TRUE, 7),
    ('LOCATION', 'LOC_FLOOR_1', '1階の物件', NULL, 'boolean', TRUE, 1),
    ('LOCATION', 'LOC_FLOOR_2UP', '2階以上', NULL, 'boolean', TRUE, 2),
    ('LOCATION', 'LOC_TOP_FLOOR', '最上階', NULL, 'boolean', TRUE, 3),
    ('LOCATION', 'LOC_CORNER', '角部屋', NULL, 'boolean', TRUE, 4),
    ('LOCATION', 'LOC_SOUTH_FACING', '南向き', NULL, 'boolean', TRUE, 5),
    ('LOCATION', 'LOC_CORNER_LOT', '角地（戸建て）', NULL, 'boolean', TRUE, 6),
    ('LOCATION', 'LOC_SOUTH_ROAD', '南道路（戸建て）', NULL, 'boolean', TRUE, 7),
    ('INTERIOR', 'INT_LAUNDRY', '室内洗濯機置場', NULL, 'boolean', TRUE, 1),
    ('INTERIOR', 'INT_WASHROOM', '洗面所独立', NULL, 'boolean', TRUE, 2),
    ('INTERIOR', 'INT_FLOORING', 'フローリング', NULL, 'boolean', TRUE, 3),
    ('INTERIOR', 'INT_LOFT', 'ロフト', NULL, 'boolean', TRUE, 4),
    ('INTERIOR', 'INT_SOUNDPROOF', '防音室', NULL, 'boolean', TRUE, 5),
    ('INTERIOR', 'INT_BASEMENT', '地下室', NULL, 'boolean', TRUE, 6),
    ('INTERIOR', 'INT_FURNISHED', '家具家電付き', NULL, 'boolean', TRUE, 7),
    ('HEATING', 'HVAC_AC', 'エアコン付き', NULL, 'boolean', TRUE, 1),
    ('HEATING', 'HVAC_FLOOR_HEAT', '床暖房', NULL, 'boolean', TRUE, 2),
    ('HEATING', 'HVAC_KEROSENE', '灯油暖房', NULL, 'boolean', TRUE, 3),
    ('HEATING', 'HVAC_GAS_HEAT', 'ガス暖房', NULL, 'boolean', TRUE, 4),
    ('BATHROOM', 'BATH_SEPARATE', 'バス・トイレ別', NULL, 'boolean', TRUE, 1),
    ('BATHROOM', 'BATH_WASHLET', '温水洗浄便座', NULL, 'boolean', TRUE, 2),
    ('BATHROOM', 'BATH_DRY', '浴室乾燥機', NULL, 'boolean', TRUE, 3),
    ('BATHROOM', 'BATH_REHEATING', '追い焚き風呂', NULL, 'boolean', TRUE, 4),
    ('BATHROOM', 'BATH_SHOWER', 'シャワールーム', NULL, 'boolean', TRUE, 5),
    ('KITCHEN', 'KITCHEN_GAS', 'ガスコンロ対応', NULL, 'boolean', TRUE, 1),
    ('KITCHEN', 'KITCHEN_IH', 'IHコンロ', NULL, 'boolean', TRUE, 2),
    ('KITCHEN', 'KITCHEN_2BURNER', 'コンロ2口以上', NULL, 'boolean', TRUE, 3),
    ('KITCHEN', 'KITCHEN_ALL_ELEC', 'オール電化', NULL, 'boolean', TRUE, 4),
    ('KITCHEN', 'KITCHEN_SYSTEM', 'システムキッチン', NULL, 'boolean', TRUE, 5),
    ('KITCHEN', 'KITCHEN_COUNTER', 'カウンターキッチン', NULL, 'boolean', TRUE, 6),
    ('KITCHEN', 'KITCHEN_DISPOSER', 'ディスポーザー', NULL, 'boolean', TRUE, 7),
    ('KITCHEN', 'KITCHEN_DISHWASHER', '食器洗い乾燥機', NULL, 'boolean', TRUE, 8),
    ('BLDG_EQUIP', 'EQUIP_PARKING', '駐車場あり', NULL, 'boolean', TRUE, 1),
    ('BLDG_EQUIP', 'EQUIP_PARKING_2', '駐車場2台以上', NULL, 'boolean', TRUE, 2),
    ('BLDG_EQUIP', 'EQUIP_PARKING_ONSITE', '敷地内駐車場', NULL, 'boolean', TRUE, 3),
    ('BLDG_EQUIP', 'EQUIP_BICYCLE', '駐輪場あり', NULL, 'boolean', TRUE, 4),
    ('BLDG_EQUIP', 'EQUIP_BIKE', 'バイク置場あり', NULL, 'boolean', TRUE, 5),
    ('BLDG_EQUIP', 'EQUIP_ELEVATOR', 'エレベーター', NULL, 'boolean', TRUE, 6),
    ('BLDG_EQUIP', 'EQUIP_DELIVERY_BOX', '宅配ボックス', NULL, 'boolean', TRUE, 7),
    ('BLDG_EQUIP', 'EQUIP_TRASH', '敷地内ゴミ置場', NULL, 'boolean', TRUE, 8),
    ('BLDG_EQUIP', 'EQUIP_TRASH_24H', '24時間ゴミ出し可', NULL, 'boolean', TRUE, 9),
    ('BLDG_EQUIP', 'EQUIP_BALCONY', 'バルコニー付き', NULL, 'boolean', TRUE, 10),
    ('BLDG_EQUIP', 'EQUIP_ROOF_BALCONY', 'ルーフバルコニー付き', NULL, 'boolean', TRUE, 11),
    ('BLDG_EQUIP', 'EQUIP_PRIVATE_GARDEN', '専用庭', NULL, 'boolean', TRUE, 12),
    ('BLDG_EQUIP', 'EQUIP_CITY_GAS', '都市ガス', NULL, 'boolean', TRUE, 13),
    ('BLDG_EQUIP', 'EQUIP_LPG', 'プロパンガス', NULL, 'boolean', TRUE, 14),
    ('BLDG_EQUIP', 'EQUIP_BARRIER_FREE', 'バリアフリー', NULL, 'boolean', TRUE, 15),
    ('SECURITY', 'SEC_AUTOLOCK', 'オートロック', NULL, 'boolean', TRUE, 1),
    ('SECURITY', 'SEC_CONCIERGE', '管理人あり', NULL, 'boolean', TRUE, 2),
    ('SECURITY', 'SEC_MONITOR_INTERCOM', 'TVモニタ付きインターホン', NULL, 'boolean', TRUE, 3),
    ('SECURITY', 'SEC_CAMERA', '防犯カメラ', NULL, 'boolean', TRUE, 4),
    ('SECURITY', 'SEC_SECURITY_CO', 'セキュリティ会社加入済', NULL, 'boolean', TRUE, 5),
    ('COMMUNICATION', 'COMM_NET_AVAILABLE', 'インターネット接続可', NULL, 'boolean', TRUE, 1),
    ('COMMUNICATION', 'COMM_NET_FREE', 'インターネット無料', NULL, 'boolean', TRUE, 2),
    ('COMMUNICATION', 'COMM_FIBER', '光ファイバー', NULL, 'boolean', TRUE, 3),
    ('COMMUNICATION', 'COMM_BS', 'BSアンテナ', NULL, 'boolean', TRUE, 4),
    ('COMMUNICATION', 'COMM_CS', 'CSアンテナ', NULL, 'boolean', TRUE, 5),
    ('COMMUNICATION', 'COMM_CABLE_TV', 'ケーブルテレビ', NULL, 'boolean', TRUE, 6),
    ('STORAGE', 'STORAGE_WIC', 'ウォークインクローゼット', NULL, 'boolean', TRUE, 1),
    ('STORAGE', 'STORAGE_SHOE', 'シューズボックス', NULL, 'boolean', TRUE, 2),
    ('STORAGE', 'STORAGE_UNDER_FLOOR', '床下収納', NULL, 'boolean', TRUE, 3),
    ('STORAGE', 'STORAGE_TRUNK', 'トランクルーム（専用）', NULL, 'boolean', TRUE, 4),
    ('MOVE_IN', 'MOVEIN_IMMEDIATE', '即入居可', NULL, 'boolean', TRUE, 1),
    ('MOVE_IN', 'MOVEIN_FEMALE_ONLY', '女性限定', NULL, 'boolean', TRUE, 2),
    ('MOVE_IN', 'MOVEIN_PET', 'ペット相談可', NULL, 'boolean', TRUE, 3),
    ('MOVE_IN', 'MOVEIN_INSTRUMENT', '楽器相談可', NULL, 'boolean', TRUE, 4),
    ('MOVE_IN', 'MOVEIN_OFFICE_USE', '事務所利用可', NULL, 'boolean', TRUE, 5),
    ('MOVE_IN', 'MOVEIN_ROOMSHARE', 'ルームシェア可', NULL, 'boolean', TRUE, 6),
    ('MOVE_IN', 'MOVEIN_SENIOR', '高齢者歓迎', NULL, 'boolean', TRUE, 7),
    ('MOVE_IN', 'MOVEIN_LGBT', 'LGBTフレンドリー', NULL, 'boolean', TRUE, 8),
    ('MOVE_IN', 'MOVEIN_CUSTOMIZE', 'カスタマイズ可', NULL, 'boolean', TRUE, 9),
    ('MOVE_IN', 'MOVEIN_DIY', 'DIY可', NULL, 'boolean', TRUE, 10),
    ('MOVE_IN', 'MOVEIN_NO_FIXED_TERM', '定期借家を含まない', NULL, 'boolean', TRUE, 11),
    ('FEAT', 'FEAT_NEW', '新築・築浅', NULL, 'boolean', TRUE, 1),
    ('FEAT', 'FEAT_REFORMED', 'リフォーム済み', NULL, 'boolean', TRUE, 2),
    ('FEAT', 'FEAT_RENOVATED', 'リノベーション物件', NULL, 'boolean', TRUE, 3),
    ('FEAT', 'FEAT_DESIGNER', 'デザイナーズ物件', NULL, 'boolean', TRUE, 4),
    ('FEAT', 'FEAT_SUBLEASE', '分譲賃貸', NULL, 'boolean', TRUE, 5),
    ('FEAT', 'FEAT_TOWER', 'タワーマンション', NULL, 'boolean', TRUE, 6),
    ('FEAT', 'FEAT_LARGE_SCALE', '大規模マンション', NULL, 'boolean', TRUE, 7),
    ('FEAT', 'FEAT_LOW_RISE', '低層マンション', NULL, 'boolean', TRUE, 8),
    ('FEAT', 'FEAT_IT_CONTRACT', 'IT重説対応', NULL, 'boolean', TRUE, 9),
    ('FEAT', 'FEAT_ONLINE_CONSULT', 'オンライン相談可', NULL, 'boolean', TRUE, 10),
    ('FEAT', 'FEAT_DUPLEX', '二世帯向き（戸建て）', NULL, 'boolean', TRUE, 11),
    ('FEAT', 'FEAT_JAPANESE_ROOM', '和室あり', NULL, 'boolean', TRUE, 12),
    ('FEAT', 'FEAT_TODAY_NEW', '本日の新着', NULL, 'boolean', TRUE, 13),
    ('FEAT', 'FEAT_WITH_PHOTO', '写真付き', NULL, 'boolean', TRUE, 14),
    ('FEAT', 'FEAT_WITH_LAYOUT', '間取り図付き', NULL, 'boolean', TRUE, 15),
    ('NEARBY', 'NEARBY_CONVENIENCE', 'コンビニ400m以内', NULL, 'boolean', TRUE, 1),
    ('NEARBY', 'NEARBY_SUPERMARKET', 'スーパー800m以内', NULL, 'boolean', TRUE, 2),
    ('NEARBY', 'NEARBY_SCHOOL', '小学校800m以内', NULL, 'boolean', TRUE, 3),
    ('NEARBY', 'NEARBY_PARK', '公園400m以内', NULL, 'boolean', TRUE, 4),
    -- ここから v2 で追加した売買固有の条件
    ('PRICE_BUY', 'PRICE_BUY_MGMT_FEE', '管理費（月額）', 'マンション売買の管理費。t_listings.mgmt_fee_monthly に格納する', 'range', FALSE, 5),
    ('PRICE_BUY', 'PRICE_BUY_REPAIR_RESERVE', '修繕積立金（月額）', 'マンション売買の修繕積立金。t_listings.repair_reserve_monthly に格納する', 'range', FALSE, 6),
    ('BUILDING', 'BLDG_TOTAL_UNITS', '総戸数', 'マンションの総戸数', 'number', FALSE, 9),
    ('FEAT', 'FEAT_VACANT', '現況空家（即引渡し可）', '中古物件が空室で引渡しが早い', 'boolean', TRUE, 16),
    ('CERT', 'CERT_INSPECTION', '建物状況調査（インスペクション）実施済', NULL, 'boolean', TRUE, 1),
    ('CERT', 'CERT_DEFECT_INSURANCE', '既存住宅売買瑕疵保険付', NULL, 'boolean', TRUE, 2),
    ('CERT', 'CERT_WARRANTY', '住宅性能保証・アフターサービス保証付', NULL, 'boolean', TRUE, 3),
    ('CERT', 'CERT_FLAT35', 'フラット35適合証明', NULL, 'boolean', TRUE, 4),
    ('CERT', 'CERT_PERFORMANCE_EVAL', '住宅性能評価書取得', NULL, 'boolean', TRUE, 5),
    ('CERT', 'CERT_SEISMIC_GRADE', '耐震等級取得', NULL, 'boolean', TRUE, 6),
    ('CERT', 'CERT_ENERGY_SAVING', '省エネ基準適合・ZEH', NULL, 'boolean', TRUE, 7),
    ('CERT', 'CERT_ANSHIN_R', '安心R住宅', '国土交通省の既存住宅の標章制度', 'boolean', TRUE, 8),
    ('LAND', 'LAND_OWNERSHIP', '権利形態：所有権', NULL, 'boolean', TRUE, 1),
    ('LAND', 'LAND_LEASEHOLD', '権利形態：借地権', NULL, 'boolean', TRUE, 2),
    ('LAND', 'LAND_ROAD_WIDTH', '前面道路幅員（m）', '接道の幅員。type_specific_attrs に原文も保持する', 'number', FALSE, 3),
    ('LAND', 'LAND_BUILDING_COVERAGE', '建ぺい率（%）', NULL, 'number', FALSE, 4),
    ('LAND', 'LAND_FLOOR_AREA_RATIO', '容積率（%）', NULL, 'number', FALSE, 5),
    ('LAND', 'LAND_USE_ZONE', '用途地域', NULL, 'enum', FALSE, 6),
    ('LAND', 'LAND_BUILD_CONDITION', '建築条件付き', '建築会社が指定される。除外条件として使うことが多い', 'boolean', TRUE, 7),
    ('LAND', 'LAND_SETBACK', 'セットバック要', '接道義務を満たすため敷地の一部を道路へ提供する必要がある', 'boolean', TRUE, 8)
) AS v(cat_code, code, name, description, data_type, is_extractable, sort_order)
JOIN m_condition_categories cat ON cat.code = v.cat_code
ON CONFLICT (code) DO UPDATE SET
    category_id    = EXCLUDED.category_id,
    name           = EXCLUDED.name,
    description    = EXCLUDED.description,
    data_type      = EXCLUDED.data_type,
    is_extractable = EXCLUDED.is_extractable,
    sort_order     = EXCLUDED.sort_order,
    updated_at     = now();
